config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
  resources :users do  
    resources :projects do
      resources :action_steps
    end
  end

  resources :projects do
    resources :action_steps
  end
  
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/action_step.rb
# == Schema Information
#
# Table name: action_steps
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  due_date    :date
#  description :text(65535)
#  project_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ActionStep < ActiveRecord::Base
  belongs_to :project
  # has_many :steps, dependent: :destroy
  
  validates_presence_of :title, :due_date, :description
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  due_date    :date
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :milestones, dependent: :destroy
  # has_many :steps, dependent: :destroy

  validates_presence_of :title, :due_date, :description
end

app/models/milestone.rb
# == Schema Information
#
# Table name: milestones
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  due_date    :date
#  description :text(65535)
#  project_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Milestone < ActiveRecord::Base
  belongs_to :project
  # has_many :steps, dependent: :destroy
  
  validates_presence_of :title, :due_date, :description
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  due_date    :date
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :action_steps, dependent: :destroy
  # has_many :steps, dependent: :destroy

  validates_presence_of :title, :due_date, :description
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/action_steps_controller.rb
class ActionStepsController < ApplicationController
  before_filter :set_project, :set_user
  before_action :set_action_step, only: [:show, :edit, :update, :destroy]

  # GET /action_steps
  def index
    @action_steps = @project.action_steps.all
  end

  # GET /action_steps/1
  def show
  end

  # GET /action_steps/new
  def new
    @action_step = @project.action_steps.new
  end

  # GET /action_steps/1/edit
  def edit
  end

  # POST /action_steps
  def create
    @action_step = @project.action_steps.new(action_step_params)

    if @action_step.save
      redirect_to project_action_step_path(@project, @action_step), notice: 'ActionStep was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /action_steps/1
  def update
    if @action_step.update(action_step_params)
      redirect_to project_action_step_path(@project, @action_step), notice: 'ActionStep was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /action_steps/1
  def destroy
    @action_step.destroy
    redirect_to project_action_steps_url(@project), notice: 'ActionStep was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_user
      @user = @project.user
    end

    def set_action_step
      @action_step = @project.action_steps.find(params[:id])
    end

   # Only allow a trusted parameter "white list" through.
    def action_step_params
      params.require(:action_step).permit(:title, :due_date, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :set_user
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = @user.projects.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = @user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = @user.projects.new(project_params)

    if @project.save
      redirect_to user_project_path(@user, @project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to user_project_path(@user, @project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to user_projects_url(@user), notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    def set_project
      @project = @user.projects.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:title, :type, :due_date, :description)
    end
end

app/helpers/action_steps_helper.rb
module ActionStepsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/action_steps/_form.html.erb
<%= form_for [@project, @action_step] do |f| %>
  <% if @action_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_step.errors.count, "error") %> prohibited this action_step from being saved:</h2>

      <ul>
      <% @action_step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_steps/edit.html.erb
<h1>Editing Action Step</h1>

<%= render 'form' %>

<%= link_to 'Show', project_action_step_path(@project, @action_step) %> |
<%= link_to 'Back', project_action_steps_path(@project) %>

app/views/action_steps/index.html.erb
<h1>Listing Action Steps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_steps.each do |action_step| %>
      <tr>
        <td><%= action_step.title %></td>
        <td><%= action_step.due_date %></td>
        <td><%= action_step.description %></td>
        <td><%= link_to 'Show', project_action_step_path(@project, action_step) %></td>
        <td><%= link_to 'Edit', edit_project_action_step_path(@project, action_step) %></td>
        <td><%= link_to 'Delete', [@project, action_step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action Step', new_project_action_step_path %>

app/views/action_steps/new.html.erb
<h1>New Action Step</h1>

<%= render 'form' %>

<%= link_to 'Back', project_action_steps_path(@project) %>

app/views/action_steps/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @action_step.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @action_step.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_step.description %>
</p>

<%= link_to 'Edit', edit_project_action_step_path(@project, @action_step) %> |
<%= link_to 'Back', project_action_steps_path(@project) %>

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="poem">
  <p class="line">Out of the night that covers me, </p>
  <p class="line">Black as the pit from pole to pole, </p>
  <p class="line">I thank whatever gods may be </p>
  <p class="line">For my unconquerable soul. </p>
  <p class="line">In the fell clutch of circumstance </p>
  <p class="line">I have not winced nor cried aloud. </p>
  <p class="line">Under the bludgeonings of chance </p>
  <p class="line">My head is bloody, but unbowed. </p>
  <p class="line">Beyond this place of wrath and tears </p>
  <p class="line">Looms but the Horror of the shade, </p>
  <p class="line">And yet the menace of the years </p>
  <p class="line">Finds and shall find me unafraid. </p>
  <p class="line">It matters not how strait the gate, </p>
  <p class="line">How charged with punishments the scroll, </p>
  <p class="line">I am the master of my fate, </p>
  <p class="line">I am the captain of my soul. </p>
  <h5>-- William Ernest Henley --</h5>
</div>

<h2>Master your fate</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MasterPlan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <h1>Master Plan</h1>
      <% if user_signed_in? %>
        <p>Logged in as <strong><%= current_user.email %></strong>.</p>
        <%= link_to 'My Projects', user_projects_path(current_user) %> |
        <%= link_to 'Edit Profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
      <hr/>
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    
    </div>
  </div>

</body>
</html>

app/views/milestones/_form.html.erb
<%= form_for [@project, @milestone] do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_for [@user, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', user_project_path(@user, @project) %> |
<%= link_to 'Back', user_projects_path(@user) %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Due date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.due_date %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', user_project_path(@user, project) %></td>
        <td><%= link_to 'Edit', edit_user_project_path(@user, project) %></td>
        <td><%= link_to 'Delete', [@user, project], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_user_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', user_projects_path %>

app/views/projects/show.html.erb
<h3>Project</h3>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
<p>
  <strong>Due date:</strong>
  <%= @project.due_date %>
</p>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
<hr/>
<% if @project.action_steps.any? %>
  <h3>Action Steps</h3>

  <% @project.action_steps.each do |action_step| %>

    <p>
      <strong>Title:</strong>
      <%= action_step.title %>
    </p>
    <p>
      <strong>Due date:</strong>
      <%= action_step.due_date %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= action_step.description %>
    </p>

    <%= link_to 'Show action_step', project_action_step_path(@project, action_step) %> |
    <%= link_to 'Edit action_step', edit_project_action_step_path(@project, action_step) %> | 
    <%= link_to 'Delete action_step', [@project, action_step], method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <hr/>
<% end %>

<%= link_to 'New action_step', new_project_action_step_path(@project) %> |
<%= link_to 'Edit Project', edit_user_project_path %> |
<%= link_to 'Back', user_projects_path %>